export const genres = [
    "ADVENTURE", "ART", "BIOGRAPHY", "CHILDREN'S", "CLASSICS", "COOKBOOKS",
    "DRAMA", "FANTASY", "FICTION", "GRAPHIC NOVELS", "HISTORICAL", "HISTORY",
    "HORROR", "HUMOR", "MEMOIR", "MUSIC", "MYSTERY", "NON-FICTION", "PHILOSOPHY",
    "POETRY", "RELIGION", "ROMANCE", "SCIENCE", "SCIENCE FICTION", "SELF-HELP",
    "SPIRITUALITY", "THRILLER", "TRAVEL", "CRIME"
];