export const genres = [
    "FICTION",
    "NON-FICTION",
    "MYSTERY",
    "THRILLER",
    "FANTASY",
    "SCIENCE FICTION",
    "HISTORICAL",
    "ROMANCE",
    "HORROR",
    "BIOGRAPHY",
    "SELF-HELP",
    "CHILDREN'S",
    "YOUNG ADULT",
    "GRAPHIC NOVELS",
    "CLASSICS",
    "POETRY",
    "ADVENTURE",
    "MEMOIR",
    "COOKBOOKS",
    "TRUE CRIME",
    "SPIRITUALITY",
    "TRAVEL",
    "SCIENCE",
    "PHILOSOPHY",
    "ART",
    "MUSIC",
    "HISTORY",
    "RELIGION",
    "HUMOR",
    "DRAMA"
];

// export default genres;